### ISSUE TITLE
Issue when using volume mounts.

### ISSUE THREAD

**Issue by SamMousa** [zixia/docker-simple-mail-forwarder#17]
When mounting a volume on `/etc` the container won't launch:

postconf: fatal: open /etc/postfix/main.cf

Shouldn't these be copied into the volume by the scripts on launch?

**Comment by zixia** [comment]
I'll be suppressed if the container could launch in this case.

The `/etc` directory contains all the system configuration files, and it's very coupling with the specific system, such as the Alpine Linux which used by SMF.

Why do you want to mount a volume on `/etc`?

**Comment by SamMousa** [comment]
Because I want to keep the data even when recreating the container (for example when I add an alias).

Why is it even registered as a volume in the `Dockerfile` if I'm not supposed to ever mount it? :)

**Comment by zixia** [comment]
I understand your requirement of adding an alias. 

Could this be done by set `SMF_CONFIG`? If it could, then you can just restart the container, without any care of the old container `/etc` data, because SMF_CONFIG will set it for you again.

And sorry for the confusing, I just had a check and found this VOLUME was introduced here:
https://github.com/zixia/docker-simple-mail-forwarder/commit/2c97ba1307c00113fd8f5cdaff5885297f778b34#diff-3254677a7917c6c01f55212f86c57fbfR55

And I totally forgot why I add this. Maybe should get rid of it later.

**Comment by SamMousa** [comment]
If you remove it then that's fine with me; the requirement of adding an alias is irrelevant for the volume. It might just have been confusion since I saw it in the `Dockerfile`.
